[package]
name = "tep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.1"
thiserror = "1.0.37"
png = "0.17.6"
getopts = "0.2.21"